
# Ecosystem Level Information
title = "Ordinals"

sub_ecosystems = []

github_organizations = []

[[repo]]
url = "https://github.com/adshao/ordinals-indexer"

[[repo]]
url = "https://github.com/alexgo-io/brc20-indexer-v1"

[[repo]]
url = "https://github.com/andrewtoth/ord"

[[repo]]
url = "https://github.com/BitCheckMe/ord"

[[repo]]
url = "https://github.com/bodily11/ord-p2p"

[[repo]]
url = "https://github.com/codeunsolved/brc20tool"

[[repo]]
url = "https://github.com/deezy-inc/deezy-place"

[[repo]]
url = "https://github.com/diba-io/bitmask-core/"

[[repo]]
url = "https://github.com/EmblemCompany/ordinals-collections"

[[repo]]
url = "https://github.com/hirosystems/ordhook"

[[repo]]
url = "https://github.com/hirosystems/ordinals-api"

[[repo]]
url = "https://github.com/hirosystems/ordinals-explorer"

[[repo]]
url = "https://github.com/kvnn/OrdControl"

[[repo]]
url = "https://github.com/lambdaclass/starknet_rollup_on_bitcoin"

[[repo]]
url = "https://github.com/luminexord/brc69"

[[repo]]
url = "https://github.com/magicoss/msigner"

[[repo]]
url = "https://github.com/mechanismHQ/zin"

[[repo]]
url = "https://github.com/metagood/OCM-Dimensions"

[[repo]]
url = "https://github.com/mkaantig/brc20-inscribe-transfer-helper"

[[repo]]
url = "https://github.com/multibit-repo"

[[repo]]
url = "https://github.com/Next-DAO/brc20_indexer"

[[repo]]
url = "https://github.com/okx/ord"

[[repo]]
url = "https://github.com/omnisat"

[[repo]]
url = "https://github.com/orbland/orb"

[[repo]]
url = "https://github.com/orc721/orditroops.starter"

[[repo]]
url = "https://github.com/orc721/rocks.starter"

[[repo]]
url = "https://github.com/ordbase/ordbase"

[[repo]]
url = "https://github.com/ordersproject/ord-api"

[[repo]]
url = "https://github.com/OrdexAi/ordex"

[[repo]]
url = "https://github.com/ordichef/indexer"

[[repo]]
url = "https://github.com/ordimint/web-app"

[[repo]]
url = "https://github.com/ordinals-wallet"

[[repo]]
url = "https://github.com/ordinals-wallet/ordinals-collections"

[[repo]]
url = "https://github.com/ordinals-wallet/wallet"

[[repo]]
url = "https://github.com/ordinals/ord"

[[repo]]
url = "https://github.com/OrdinalSafe/ordinalsafe-extension"

[[repo]]
url = "https://github.com/orenyomtov/openordex"

[[repo]]
url = "https://github.com/sadoprotocol/ordit"

[[repo]]
url = "https://github.com/sadoprotocol/saline"

[[repo]]
url = "https://github.com/satsnames/satsnamesapi"

[[repo]]
url = "https://github.com/thaddeusdiamond/btc-dapp-js"

[[repo]]
url = "https://github.com/tizzle/sats-names-xyz"

[[repo]]
url = "https://github.com/tyjvazum/arb"

[[repo]]
url = "https://github.com/unisat-wallet"

[[repo]]
url = "https://github.com/unisat-wallet/extension"

[[repo]]
url = "https://github.com/UTXORD/utxord-wallet"

[[repo]]
url = "https://github.com/0xmajin/btc_ord_5.0"

[[repo]]
url = "https://github.com/mksipe/NoMoreOrd"

[[repo]]
url = "https://github.com/monograms/brc20-check"

[[repo]]
url = "https://github.com/patrykq9/bitcoin-ordinals-wallet"

[[repo]]
url = "https://github.com/Wenlinhan/Ordinal-NFT"

[[repo]]
url = "https://github.com/YemmyFolayan/BRC20-Brise-Token-Swap"