# Ecosystem Level Information
title = "Ordinals"

sub_ecosystems = []

github_organizations = []

# Repositories
[[repo]]
url = "https://github.com/satsnames/satsnamesapi"

[[repo]]
url = "https://github.com/ordimint/web-app"

[[repo]]
url = "https://github.com/Next-DAO/brc20_indexer"

[[repo]]
url = "https://github.com/unisat-wallet/extension"

[[repo]]
url = "https://github.com/hirosystems/ordhook"

[[repo]]
url = "https://github.com/orc721/rocks.starter"

[[repo]]
url = "https://github.com/orc721/orditroops.starter"

[[repo]]
url = "https://github.com/ordbase/ordbase"

[[repo]]
url = "https://github.com/hirosystems/ordinals-api"

[[repo]]
url = "https://github.com/hirosystems/ordinals-explorer"

[[repo]]
url = "https://github.com/hirosystems/chainhook"

[[repo]]
url = "https://github.com/deezy-inc/deezy-place"

[[repo]]
url = "https://github.com/magicoss/msigner"

[[repo]]
url = "https://github.com/metagood/OCM-Dimensions"

[[repo]]
url = "https://github.com/UTXORD/utxord-wallet"

[[repo]]
url = "https://github.com/sadoprotocol/ordit"

[[repo]]
url = "https://github.com/mechanismHQ/metroid"

[[repo]]
url = "https://github.com/ordinals-wallet/wallet"

[[repo]]
url = "https://github.com/sadoprotocol/saline"

[[repo]]
url = "https://github.com/OrdinalSafe/ordinalsafe-extension"

[[repo]]
url = "https://github.com/ordichef/indexer"

[[repo]]
url = "https://github.com/adshao/ordinals-indexer"

[[repo]]
url = "https://github.com/tizzle/sats-names-xyz"

[[repo]]
url = "https://github.com/thaddeusdiamond/btc-dapp-js"

[[repo]]
url = "https://github.com/kvnn/OrdControl"